### ISSUE TITLE
Perpetual drift on description for default_connector in cloudconnexa_network resource

### ISSUE THREAD

**Issue by pickgr** [OpenVPN/cloudconnexa-go-client#14]
This is a regression that was introduced in 0.1.0 in the new provider.

There is now a default description "Managed by Terraform." if it is not specified.  However, when applying the description, drift still shows and the resource is never actually updated.

Sample code:

```
resource "cloudconnexa_network" "foo" {
  description     = "Testing"
  egress          = true
  internet_access = "LOCAL"
  name            = "foo"

  default_connector {
    name          = "foo"
    vpn_region_id = var.region_id
  }

  default_route {
    description = "Testing"
    subnet      = var.subnet
    type        = "IP_V4"
  }

}
```

A work-around is to add

```
  lifecycle {
    ignore_changes = [
      default_connector[0].description
    ]
  }
```

Sample plan output:

```
Terraform will perform the following actions:

  # module.connexa.cloudconnexa_network.sc_bench will be updated in-place
  ~ resource "cloudconnexa_network" "foo" {
        id              = "1234"
        name            = "foo"
        # (4 unchanged attributes hidden)

      ~ default_connector {
          + description       = "Managed by Terraform."
            id                = "5678"
            name              = "foo"
            # (6 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

After `terraform apply`, the same plan output is shown and a description is not added to the `default_connector`

**Comment by sahaqaa** [comment]
I will take a look and try to fix it

**Comment by sahaqaa** [comment]
@pickgr This should be fixed in new release: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/0.1.2
Feel free to test and close this issue if all will be OK.

**Comment by pickgr** [comment]
Hi @sahaqaa I believe the original issue is now fixed.  I was able to remove my `ignore_changes` work-around and the drift is no longer present in the `cloudconnexa_network` resource after adding a description to each default connector.

Unfortunately, it looks like a regression may have been introduced on the `cloudconnexa_connector` resource where it now shows drift with existing resource on the optional description.  Note that this is especially dangerous as the resource will be destroyed and recreated.


Sample code:

```
resource "cloudconnexa_connector" "secondary" {
  description       = "Test description"
  name              = "secondary"
  network_item_id   = cloudconnexa_network.this[each.key].id
  network_item_type = "NETWORK"
  vpn_region_id     = each.value.vpn_region_id
}
```

Plan:
```
Terraform will perform the following actions:

  # module.connexa.cloudconnexa_connector.secondary["aws-vpc-prd"] must be replaced
-/+ resource "cloudconnexa_connector" "secondary" {
      + description       = "Test description" # forces replacement
      ~ id                = "018864b2-59d1-4180-b835-916f65128eb4" -> (known after apply)
      ~ ip_v4_address     = "10.11.0.102/28" -> (known after apply)
      ~ ip_v6_address     = "fd:0:0:8106::6/64" -> (known after apply)
        name              = "secondary"
.
.
.
```

Again, a work-around for this is to add the lifecycle to the resource:

```
  lifecycle {
    ignore_changes = [
      description
    ]
  }
```

I hope this is enough information. Thank you for the help!
