### ISSUE TITLE
connector update missing

### ISSUE THREAD

**Issue by chicco785** [OpenVPN/cloudconnexa-go-client#15]
this would be required to update connectors without destroying them

**Comment by sahaqaa** [comment]
@chicco785 I've created issue directly to the provider, https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues/12
It will be better place to have this for visibility because issues here (https://github.com/OpenVPN/cloudconnexa-go-client/issues) are for Client.

**Comment by chicco785** [comment]
yep, the issue was here because I thought the client did not have the update method
